"""Données d'exercices Anglais (Aon/cut-e English & Orientation).

AIS : (phrase à trou, bonne réponse, [3 leurres], piège)
VOC : (définition, mot cible, [3 leurres], piège)
ORT : (orthographe correcte, fautive 1, fautive 2, piège)
"""

AIS = [
    ("The new regulation will come ___ force on 1 January.", "into", ["in", "at", "on"],
     "« in force » n'existe pas : c'est **come into force** (entrer en vigueur)."),
    ("Payment must be made ___ the 15th at the latest.", "by", ["on", "at", "until"],
     "**by** = au plus tard (date limite) ; « until the 15th » = jusqu'au 15 (durée)."),
    ("We will deliver the goods ___ time.", "on", ["in", "by", "at"],
     "**on time** = à l'heure ; **in time** = à temps (avant la limite)."),
    ("She signed the contract ___ behalf of the company.", "on", ["in", "at", "for"],
     "expression figée : **on behalf of** (au nom de)."),
    ("The report focuses ___ cost reduction.", "on", ["in", "at", "over"],
     "**focus on** ; « focus in » = faute fréquente."),
    ("They invested heavily ___ renewable energy.", "in", ["on", "at", "to"],
     "**invest in** (pas « invest on »)."),
    ("The merger was completed ___ the end of March.", "by", ["on", "in", "at"],
     "**by the end of** = avant la fin de ; « at the end of » = au moment de la fin."),
    ("Profits rose ___ 12% last year.", "by", ["of", "to", "at"],
     "montant de la hausse = **by** ; niveau atteint = **to**."),
    ("Sales increased ___ 12% to reach €4m.", "by", ["of", "at", "for"],
     "idem : la progression se dit **by**, jamais « of »."),
    ("He is in charge ___ the audit team.", "of", ["for", "with", "about"],
     "**in charge of** ; « responsible for » mais « in charge of »."),
    ("The project consists ___ three phases.", "of", ["in", "with", "from"],
     "**consist of** ; « consist in » = consister à (sens différent)."),
    ("We are looking forward ___ your reply.", "to", ["for", "at", "on"],
     "**look forward to + nom/-ing** (jamais « look forward to hear »)."),
    ("The board agreed ___ the proposal.", "to", ["with", "on", "for"],
     "**agree to** une proposition / **agree with** une personne."),
    ("Please find ___ the annual report.", "enclosed", ["attached with", "enclosed in", "attached to"],
     "**enclosed / attached** seuls ; « attached with » = faute."),
    ("The subsidiary ___ by the CFO is based in Lyon.", "run", ["ran", "running", "runs"],
     "participe passé passif : **run by** (dirigée par)."),
    ("The loan was ___ by the credit committee.", "approved", ["approve", "approving", "approval"],
     "passif : was + participe passé (**approved**), pas le nom."),
    ("Interest rates have ___ significantly this year.", "risen", ["raised", "rised", "rose"],
     "**rise–rose–risen** (intransitif) ; « raise » = augmenter qqch."),
    ("The central bank ___ interest rates twice.", "raised", ["rose", "rised", "risen"],
     "**raise** = augmenter qqch (transitif) ; la banque « raises » les taux."),
    ("Our costs are ___ than last year.", "higher", ["more high", "highest", "high"],
     "comparatif de « high » = **higher** (jamais « more high »)."),
    ("This was our ___ profitable quarter.", "most", ["more", "best", "much"],
     "superlatif d'un adjectif long : **the most profitable**."),
    ("He works ___ than anyone in the team.", "harder", ["more hard", "hardest", "hardly"],
     "**harder** (comparatif de hard) ; « hardly » = à peine (piège de sens)."),
    ("The invoice must be paid ___ 30 days.", "within", ["during", "for", "to"],
     "**within 30 days** (dans un délai de) ; « during » = pendant un événement."),
    ("She has worked here ___ 2019.", "since", ["for", "during", "from"],
     "**since** + point de départ ; **for** + durée."),
    ("We have known them ___ ten years.", "for", ["since", "during", "from"],
     "**for** + durée (ten years)."),
    ("The agreement was ___ yesterday.", "signed", ["sign", "signing", "signs"],
     "passif au passé : **was signed**."),
    ("He is ___ for the departmental budget.", "responsible", ["responsibility", "responsibly", "responsive"],
     "adjectif après « be » : **responsible** (pas le nom ni l'adverbe)."),
    ("The decision had a major ___ on our results.", "impact", ["impacted", "impacting", "impacts"],
     "après « a major » il faut un **nom** : impact."),
    ("We need to ___ our operating costs.", "reduce", ["reduction", "reducing", "reductive"],
     "après « to » (infinitif de but) : **reduce**."),
    ("The ___ of the company rose sharply.", "value", ["valuable", "valued", "valuably"],
     "après « the » : nom **value**."),
    ("Their offer was ___ generous.", "extremely", ["extreme", "extremity", "extremes"],
     "adverbe devant un adjectif : **extremely generous**."),
    ("The audit was carried ___ thoroughly.", "out", ["in", "off", "up"],
     "**carry out** = mener ; « carry on » = continuer."),
    ("The deal ___ through despite the delays.", "went", ["came", "ran", "took"],
     "**go through** = aboutir ; « come through » = survivre/recevoir."),
    ("They had to ___ the meeting off.", "call", ["put", "make", "take"],
     "**call off** = annuler."),
    ("Please ___ up the figures before Friday.", "add", ["total", "count", "sum"],
     "**add up** = additionner (« total up » existe mais est rare ; « count up » ≠)."),
    ("The company will ___ off 200 employees.", "lay", ["put", "set", "take"],
     "**lay off** = licencier ; « put off » = reporter."),
    ("We must ___ up with the new rules.", "keep", ["hold", "stay", "catch"],
     "**keep up with** = suivre le rythme ; « catch up with » = rattraper un retard."),
    ("She will ___ over as CFO in June.", "take", ["get", "make", "put"],
     "**take over** = prendre la relève."),
    ("The old IT system was gradually ___ out.", "phased", ["taken", "put", "given"],
     "**phase out** = supprimer progressivement."),
    ("He ___ for the accounting error.", "apologised", ["excused", "forgave", "regretted"],
     "**apologise for** = s'excuser de ; « excuse » = excuser qqn."),
    ("Prices are ___ to rise next quarter.", "expected", ["expecting", "expectedly", "expects"],
     "tournure passive : **be expected to**."),
    ("If the rate ___ , we will renegotiate.", "rises", ["raises", "rised", "rose"],
     "conditionnel réel : if + présent ; « rise » intransitif (le taux monte seul)."),
    ("Unless payment ___ , supply will be suspended.", "is received", ["receives", "will receive", "received"],
     "passif + pas de « will » après unless : **is received**."),
    ("Yesterday the board ___ the annual results.", "approved", ["approves", "approving", "approve"],
     "**yesterday** → prétérit simple (pas de present perfect)."),
    ("Tomorrow we ___ the new compliance policy.", "will adopt", ["adopted", "have adopted", "adopting"],
     "**tomorrow** → futur ; « adopt » = adopter, « adapt » = adapter."),
    ("The figures ___ been verified by the auditors.", "have", ["has", "is", "are"],
     "**figures** = pluriel → have."),
    ("Neither the CFO nor the auditors ___ present.", "were", ["was", "is", "been"],
     "accord avec le sujet le plus proche (auditors → pluriel)."),
    ("A number of clients ___ complained about the fees.", "have", ["has", "is", "was"],
     "**a number of** = pluriel (≠ « the number of » = singulier)."),
    ("He suggested ___ the deadline.", "extending", ["to extend", "extend", "extended"],
     "**suggest + -ing** (jamais « suggest to do »)."),
    ("We decided ___ the offer.", "to accept", ["accepting", "accept", "accepted"],
     "**decide to + infinitif**."),
    ("They avoid ___ about the risks.", "talking", ["to talk", "talk", "talked"],
     "**avoid + -ing**."),
    ("The firm succeeded ___ raising €50m.", "in", ["to", "on", "for"],
     "**succeed in + -ing**."),
    ("He is good ___ negotiations.", "at", ["in", "on", "for"],
     "**good at** (compétence)."),
    ("These results differ ___ last year's.", "from", ["of", "with", "to"],
     "**differ from**."),
    ("This product is superior ___ the old one.", "to", ["than", "of", "from"],
     "**superior to** (pas « than », malgré le comparatif)."),
    ("We spent €2m ___ marketing.", "on", ["in", "at", "for"],
     "**spend money on**."),
    ("She is keen ___ expanding abroad.", "on", ["in", "at", "to"],
     "**keen on + -ing**."),
    ("The audit complied ___ the new standards.", "with", ["to", "on", "for"],
     "**comply with**."),
    ("The contract is subject ___ board approval.", "to", ["of", "for", "with"],
     "**subject to**."),
    ("Please refer ___ the appendix for details.", "to", ["on", "at", "for"],
     "**refer to**."),
    ("The manager insisted ___ an internal review.", "on", ["in", "for", "at"],
     "**insist on**."),
    ("They apologised ___ the late delivery.", "for", ["about", "to", "of"],
     "**apologise for** qqch / **apologise to** qqn."),
    ("He was accused ___ insider trading.", "of", ["for", "with", "about"],
     "**accuse someone of**."),
    ("The firm specialises ___ asset management.", "in", ["on", "at", "for"],
     "**specialise in** (UK) / specialize in (US)."),
    ("The shares ___ by 4% on Friday.", "fell", ["felt", "filled", "failed"],
     "**fell** = passé de fall (baisser) ; « felt » = passé de feel."),
    ("The company ___ its workforce by 10% last year.", "cut", ["cutted", "cutten", "cutting"],
     "**cut–cut–cut** (invariable)."),
    ("There has been a sharp ___ in demand.", "fall", ["fell", "feel", "felt"],
     "après « a sharp » : nom **fall**."),
    ("The supplier went ___ last month.", "bankrupt", ["bankruptcy", "bank", "banking"],
     "**go bankrupt** (adjectif) ; « bankruptcy » = nom (faillite)."),
    ("The deal is likely to ___ through next week.", "go", ["pass", "walk", "run"],
     "**go through** = se conclure."),
    ("Our ___ with that bank dates from 2010.", "relationship", ["relation", "relating", "relative"],
     "lien commercial durable = **relationship** ; « relation » = lien logique/familial."),
]

VOC = [
    ("to postpone or delay an event", "defer", ["infer", "refer", "confer"],
     "leurres de forme : infer=déduire, refer=renvoyer, confer=consulter."),
    ("to deduce from evidence", "infer", ["defer", "confer", "refer"],
     "infer = déduire ; ne pas confondre avec defer (reporter)."),
    ("to consult someone before deciding", "confer", ["defer", "infer", "prefer"],
     "confer = se concerter."),
    ("money lent that must be repaid", "loan", ["debt", "deposit", "lease"],
     "loan = le prêt accordé ; debt = la dette due."),
    ("money that is owed", "debt", ["loan", "asset", "credit"],
     "debt = somme due (le « b » est muet)."),
    ("the person who receives payment", "payee", ["payer", "broker", "debtor"],
     "payee = bénéficiaire ; payer = payeur."),
    ("an official order to pay money", "warrant", ["warranty", "warning", "warden"],
     "warrant = mandat/ordre ; warranty = garantie produit."),
    ("a written promise to repair or replace", "warranty", ["warrant", "warehouse", "warden"],
     "warranty = garantie commerciale."),
    ("the amount by which revenue exceeds cost", "profit", ["turnover", "margin", "revenue"],
     "profit = résultat net ; turnover = chiffre d'affaires."),
    ("the total income from sales", "revenue", ["profit", "yield", "dividend"],
     "revenue/turnover = CA, avant charges."),
    ("a payment made to shareholders", "dividend", ["interest", "royalty", "coupon"],
     "dividend = dividende ; interest = intérêt (dette)."),
    ("the income earned on a loan or deposit", "interest", ["dividend", "yield", "fee"],
     "interest = intérêt (prêt/dépôt)."),
    ("to officially cancel a law or contract", "revoke", ["recall", "repeal", "recover"],
     "revoke = révoquer ; repeal = abroger une loi."),
    ("to say again or restate", "reiterate", ["iterate", "irrigate", "integrate"],
     "reiterate = réaffirmer."),
    ("to examine official records", "audit", ["account", "assess", "arbitrate"],
     "audit = vérification formelle des comptes."),
    ("a person who buys shares", "investor", ["creditor", "debtor", "auditor"],
     "investor = investisseur ; creditor = créancier."),
    ("a person or firm owed money", "creditor", ["debtor", "investor", "borrower"],
     "creditor = créancier ; debtor = débiteur."),
    ("a person who owes money", "debtor", ["creditor", "lender", "payee"],
     "debtor = débiteur (celui qui doit)."),
    ("to give up a right or claim", "waive", ["wave", "weave", "waver"],
     "waive = renoncer à ; wave = saluer/vague (piège de sens)."),
    ("a rise or growth in value or size", "increase", ["decrease", "increment", "interest"],
     "increase (nom) = augmentation ; increment = pas d'incrémentation."),
    ("a fall in value or size", "decrease", ["increase", "deficit", "deduction"],
     "decrease = baisse."),
    ("money kept back from a payment", "deduction", ["discount", "deficit", "deposit"],
     "deduction = retenue ; discount = remise."),
    ("a reduction in price granted to a buyer", "discount", ["deduction", "rebate", "deposit"],
     "discount = remise commerciale."),
    ("a partial refund after purchase", "rebate", ["discount", "refund", "credit"],
     "rebate = ristourne ; refund = remboursement intégral/partiel."),
    ("money paid regularly for the use of property", "rent", ["lease", "rate", "fee"],
     "rent = loyer payé ; lease = le contrat de location."),
    ("a contract giving the right to use property", "lease", ["rent", "loan", "deed"],
     "lease = bail ; rent = le paiement."),
    ("a written legal document proving ownership", "deed", ["deal", "draft", "duty"],
     "deed = acte notarié."),
    ("a sum paid as security for a contract", "deposit", ["down payment", "installment", "premium"],
     "deposit = caution/acompte ; installment = échéance."),
    ("one of several regular payments", "installment", ["deposit", "invoice", "annuity"],
     "installment = versement échelonné."),
    ("a bill requesting payment", "invoice", ["receipt", "quote", "voucher"],
     "invoice = facture ; receipt = reçu (preuve de paiement)."),
    ("a written proof that payment was made", "receipt", ["invoice", "voucher", "statement"],
     "receipt : le « p » est muet."),
    ("a document that gives the holder a right", "voucher", ["receipt", "coupon", "warrant"],
     "voucher = bon/chèque-cadeau."),
    ("a formal written proposal", "tender", ["vendor", "letter", "draft"],
     "tender = offre formelle (appel d'offres)."),
    ("a seller or supplier", "vendor", ["tender", "buyer", "broker"],
     "vendor = vendeur ; tender = offre."),
    ("a person who arranges deals for others", "broker", ["dealer", "agent", "vendor"],
     "broker = courtier (intermédiaire)."),
    ("a person who buys and sells for their own account", "dealer", ["broker", "agent", "trustee"],
     "dealer = négociant (pour son propre compte)."),
    ("a person legally managing assets for another", "trustee", ["executor", "agent", "auditor"],
     "trustee = fiduciaire ; executor = exécuteur testamentaire."),
    ("to state the value of an asset", "appraise", ["apprise", "raise", "praise"],
     "appraise = évaluer ; apprise = informer (piège classique)."),
    ("to inform someone", "apprise", ["appraise", "prize", "advise"],
     "apprise = informer."),
    ("to make an asset less valuable on the books", "depreciate", ["devalue", "dilute", "deflate"],
     "depreciate = amortir (comptable) ; devalue = dévaluer (monnaie)."),
    ("to spread the cost of an asset over its life", "amortise", ["depreciate", "allocate", "accrue"],
     "amortise = amortir un actif incorporel/un emprunt."),
    ("to record revenue or cost as it is earned", "accrue", ["amortise", "allocate", "invoice"],
     "accrue = comptabiliser d'avance (charges/produits à payer)."),
    ("to set aside money for a specific purpose", "allocate", ["accrue", "assign", "amortise"],
     "allocate = affecter un budget."),
    ("the total value of a company's shares", "market capitalisation", ["book value", "equity", "turnover"],
     "market cap = cours × nombre d'actions."),
    ("the value of assets minus liabilities", "net assets", ["gross assets", "market cap", "turnover"],
     "net assets = actif net (capitaux propres)."),
    ("profit expressed as a percentage of revenue", "margin", ["yield", "return", "markup"],
     "margin = marge ; markup = majoration sur coût."),
    ("income from an investment, in %", "yield", ["margin", "interest", "return"],
     "yield = rendement d'un placement."),
    ("money borrowed by a company via bonds", "debt", ["equity", "share", "asset"],
     "debt = financement par dette ; equity = par actions."),
    ("ownership interest in a company", "equity", ["debt", "liability", "credit"],
     "equity = capitaux propres / actions."),
    ("a formal examination of a case", "hearing", ["trial", "appeal", "verdict"],
     "hearing = audience ; verdict = décision du jury."),
    ("a written statement made under oath", "affidavit", ["testimony", "subpoena", "plea"],
     "affidavit = déclaration sous serment écrite."),
    ("an official order to appear in court", "subpoena", ["warrant", "summons", "plea"],
     "subpoena = assignation à comparaître."),
    ("a formal accusation of a crime", "indictment", ["verdict", "sentence", "plea"],
     "indictment = mise en accusation (« c » muet)."),
    ("a person who owns shares", "shareholder", ["stakeholder", "bondholder", "debtholder"],
     "shareholder = actionnaire ; stakeholder = partie prenante."),
    ("a person with an interest in the business", "stakeholder", ["shareholder", "investor", "creditor"],
     "stakeholder = partie prenante (plus large qu'actionnaire)."),
    ("to examine very closely", "scrutinise", ["overlook", "oversee", "overrule"],
     "scrutinise = examiner de près ; overlook = ne pas remarquer (contresens !)."),
    ("to fail to notice something", "overlook", ["scrutinise", "oversee", "overrate"],
     "overlook = laisser passer (≠ examiner)."),
    ("to supervise work", "oversee", ["overlook", "overrule", "overtake"],
     "oversee = superviser ; oversee ≠ overlook."),
    ("stingy, unwilling to spend", "miserly", ["generous", "thrifty", "lavish"],
     "miserly = avare ; thrifty = économe (positif) ; generous = contraire."),
    ("economical, avoiding waste", "thrifty", ["miserly", "lavish", "generous"],
     "thrifty = économe (positif)."),
    ("spending too freely", "lavish", ["thrifty", "frugal", "modest"],
     "lavish = fastueux ; frugal = sobre."),
    ("causing a harmful effect", "detrimental", ["beneficial", "neutral", "marginal"],
     "detrimental = nuisible ; beneficial = contraire."),
    ("likely to happen soon", "imminent", ["eminent", "prominent", "immanent"],
     "imminent = imminent ; eminent = éminent (piège de forme)."),
    ("famous and respected", "eminent", ["imminent", "prominent", "permanent"],
     "eminent = éminent, illustre."),
    ("clearly visible or important", "prominent", ["eminent", "imminent", "dominant"],
     "prominent = de premier plan."),
    ("to put into practice", "implement", ["complement", "supplement", "compliment"],
     "implement = mettre en œuvre ; complement = compléter ; compliment = féliciter."),
    ("to complete or go well with", "complement", ["compliment", "implement", "supplement"],
     "complement (e) = compléter ; compliment (i) = féliciter."),
    ("to add something extra", "supplement", ["complement", "implement", "amplify"],
     "supplement = ajouter en plus."),
    ("required by rules or law", "mandatory", ["optional", "voluntary", "facultative"],
     "mandatory = obligatoire ; optional = contraire."),
    ("allowed but not required", "optional", ["mandatory", "compulsory", "binding"],
     "optional = facultatif."),
    ("legally binding", "binding", ["optional", "advisory", "tentative"],
     "binding = contraignant."),
    ("based on observation rather than theory", "empirical", ["theoretical", "hypothetical", "anecdotal"],
     "empirical = fondé sur les données."),
    ("assumed for the sake of argument", "hypothetical", ["empirical", "proven", "actual"],
     "hypothetical = supposé."),
    ("occurring at irregular intervals", "sporadic", ["constant", "steady", "periodic"],
     "sporadic = ponctuel/irrégulier ; periodic = périodique (régulier)."),
    ("happening repeatedly at fixed intervals", "periodic", ["sporadic", "random", "occasional"],
     "periodic = périodique."),
    ("able to be relied on", "reliable", ["liable", "liable", "credible"],
     "reliable = fiable ; liable = responsable juridiquement."),
    ("legally responsible", "liable", ["reliable", "credible", "durable"],
     "liable for = responsable de."),
    ("a sudden sharp fall", "slump", ["surge", "spike", "rally"],
     "slump = effondrement ; surge = envolée (contraire)."),
    ("a sudden sharp rise", "surge", ["slump", "dip", "decline"],
     "surge = forte hausse."),
    ("a short-term recovery in prices", "rally", ["slump", "crash", "spike"],
     "rally = rebond."),
    ("to reduce the number of staff", "downsize", ["outsource", "upsize", "sideline"],
     "downsize = réduire les effectifs ; outsource = externaliser."),
    ("to contract work to an outside firm", "outsource", ["downsize", "offshore", "insource"],
     "outsource = externaliser (offshore = délocaliser à l'étranger)."),
    ("to buy out a competitor", "acquire", ["merge", "divest", "liquidate"],
     "acquire = racheter ; merge = fusionner (deux entités)."),
    ("to sell off a business unit", "divest", ["invest", "acquire", "convert"],
     "divest = céder (≠ invest, sens inverse)."),
    ("to close a company and sell its assets", "liquidate", ["liquid", "liquidise", "litigate"],
     "liquidate = liquider ; litigate = aller en justice."),
    ("money received in advance for future service", "deferred income", ["accrued income", "prepaid expense", "reserve"],
     "deferred income = produit constaté d'avance."),
    ("an expense paid before it is incurred", "prepaid expense", ["accrued expense", "deferred income", "provision"],
     "prepaid = payé d'avance (actif) ; accrued = dû (passif)."),
]

ORT = [
    ("accommodate", "accomodate", "acommodate", "deux « c », deux « m »."),
    ("acknowledgement", "acknowlegement", "acknowledgment", "UK garde le « e » (US : acknowledgment)."),
    ("acquisition", "aquisition", "acquizition", "« cq » puis « u » : ac-qui-si-tion."),
    ("analyse", "analize", "annalyse", "UK : -yse ; US : analyze (un seul « n »)."),
    ("bankruptcy", "bankrupcy", "bankrupty", "ban-krupt-cy (le « t » reste)."),
    ("beneficiary", "benefeciary", "beneficary", "-fi-ciary."),
    ("bureau", "beaureau", "bureaau", "bu-reau."),
    ("calendar", "calender", "calandar", "-dar (pas -der)."),
    ("cancellation", "cancelation", "cancelattion", "deux « l » au UK."),
    ("catalogue", "catalouge", "catalog", "UK : catalogue."),
    ("cheque", "check", "cheak", "UK : cheque (paiement) ; check = vérifier."),
    ("collateral", "colateral", "collatoral", "deux « l » au début."),
    ("commission", "comission", "commision", "deux « m », deux « s »."),
    ("commitment", "comitment", "committement", "commit + ment (un seul « t » final)."),
    ("consensus", "concensus", "consencus", "cons-ensus (pas de « c »)."),
    ("creditor", "creaditor", "creditour", "creditor."),
    ("curriculum", "curiculum", "curicculum", "deux « r »."),
    ("debtor", "debter", "debtour", "le « b » est muet mais s'écrit."),
    ("depreciation", "depreciaton", "depretiation", "de-pre-ci-a-tion (pas -tion-)."),
    ("dividend", "divident", "dividende", "-end (pas -ent)."),
    ("due diligence", "dew diligence", "due dilligence", "diligence : un seul « l » après i."),
    ("eligible", "elegible", "eligable", "é-li-gible."),
    ("equity", "equitty", "eqity", "deux « t » ? non : e-qui-ty."),
    ("exceed", "excede", "exseed", "ex-ceed (ee puis d)."),
    ("expense", "expence", "expanses", "-ense (pas -ence)."),
    ("foreign", "foriegn", "foregin", "ei après g : for-eign."),
    ("guarantee", "guarentee", "gaurantee", "gua-ran-tee."),
    ("hierarchy", "hierachy", "hierarchy", "hie-rar-chy."),
    ("instalment", "installment", "instalmant", "UK : instalment ; US : installment."),
    ("invoice", "invioce", "invoise", "in-voice."),
    ("judgement", "judgment", "jugdement", "UK : judgement ; US : judgment."),
    ("liability", "liabilty", "liablity", "lia-bi-li-ty."),
    ("licence", "license", "lisence", "UK : licence (nom) / license (verbe)."),
    ("maintenance", "maintainance", "maintenence", "main-te-nance (pas -tain-)."),
    ("mortgage", "morgage", "mortage", "le « t » s'écrit mais ne se prononce pas."),
    ("negotiate", "negociate", "negosiate", "ne-go-ci-ate (« g »)."),
    ("occurrence", "occurence", "ocurrence", "deux « c », deux « r »."),
    ("personnel", "personel", "personal", "personnel = le personnel (2 n) ; personal = privé."),
    ("prepaid", "prepayed", "pre-payed", "pre + paid."),
    ("programme", "program", "programe", "UK : programme (sauf informatique : program)."),
    ("questionnaire", "questionaire", "questionnair", "deux « n » après questio-."),
    ("receipt", "reciept", "receit", "le « p » est muet : re-ceipt."),
    ("recommend", "recomend", "recommand", "un « c », deux « m »."),
    ("referendum", "referrendum", "referandum", "un seul « r » au milieu."),
    ("seize", "sieze", "seaze", "ei après z : seize."),
    ("separate", "seperate", "separete", "un « a » au milieu : sep-a-rate."),
    ("solvency", "solvancy", "solvenci", "sol-ven-cy."),
    ("successful", "sucessful", "succesful", "deux « c », deux « s »."),
    ("sufficient", "sufficent", "suficient", "suf-fi-cient."),
    ("supersede", "supercede", "superseed", "super-sede (un seul s au milieu)."),
    ("threshold", "threshhold", "treshold", "thres-hold (un seul h)."),
    ("turnover", "turn-over", "turnoverr", "UK : turnover en un seul mot, sans tiret."),
    ("until", "untill", "untile", "un seul « l » final."),
    ("vacancy", "vacency", "vacancie", "va-can-cy."),
    ("warehouse", "warehousse", "wearhouse", "ware + house."),
    ("whereas", "wheras", "whereas", "where + as."),
    ("withhold", "withold", "with-hold", "with + hold (deux h)."),
    ("write-off", "right-off", "rite-off", "write = écrire (homophone de right)."),
    ("yield", "yeild", "yeld", "y-i-e-l-d."),
    ("acknowledge", "aknowledge", "acknowlege", "deux « l » ? non : un « c » + « kn »."),
    ("arrears", "arreas", "arrears", "ar-rears (argent dû en retard)."),
]
